
[general]

output_directory = "test_results_HCF343837"
log_interval_seconds = 1

################################################################################
#  DEVICE UNDER TEST (DUT) LIST
################################################################################

[[duts]]
#hash: 07a7
name = "DUT1"
cpu_id = "0A0017000950325557323120"
relay_port = 1

[[duts]]
#hash: ae4c
name = "DUT2"
cpu_id = "1E0018000950325557323120"
#relay_port = 1

[[duts]]
#hash: 3800
name = "DUT3"
cpu_id = "1C0017000950325557323120"
#relay_port = 1

[[duts]]
#hash: eb95
name = "DUT4"
cpu_id = "210013000A50325557323120"
#relay_port = 1

[[duts]]
#hash: 8140
name = "DUT5"
cpu_id = "2C0018000950325557323120"
#relay_port = 1

################################################################################
#  RELAY BOADR (DEDITEC) SETTINGS
################################################################################

[relay]
ip_address = "192.168.1.10" # Deditec board IP address

################################################################################
#  TEST PLAN
################################################################################

[test_plan]

temperatures_celsius = [25, 30, 20, 35, 15, 40, 10, 45, 5, 0, 25] # Temp scenario lists
cycles_per_temperature = 1
test_modes = ["linear", "switching"] # Test modes run in every cycle

# Linear test mode parameters
linear_discharge_load = 0 # could be set in range 0-255
linear_relaxation_time_min = 60

# Switching test mode parameters
switching_discharge_switch_cycle_min = 5 # Time interval between switching load step
switching_relaxation_time_min = 60

# Random wonder test mode parameters
random_wonder_core_test_time_min = 120
random_wonder_relaxation_time_min = 30

################################################################################
#  NOTIFICATION SETTINGS
################################################################################

[notifications]
notification_channel = "slack"

slack_webhook_url = "<Fill your webhook URL>"


